export const actionTypes = {
  FETCH_MAP_POSITION: 'FETCH_MAP_POSITION',
  SAVE_MAP_POSITION: 'SAVE_MAP_POSITION',
  SET_DEFAULT_MAP_POSITION: 'SET_DEFAULT_MAP_POSITION',

  FETCH_MEMBERS_COMPLETED: 'FETCH_MEMBERS_COMPLETED',
  FETCH_MEMBER_BY_ID_COMPLETED: 'FETCH_MEMBER_BY_ID_COMPLETED',
  UPDATE_MEMBER_FIELD: 'UPDATE_MEMBER_FIELD',
  SAVE_MEMBER: 'SAVE_MEMBER',
};
