# --- !Ups

CREATE TABLE `MAP_POSITION` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) DEFAULT NULL,
  `LAT` double NOT NULL,
  `LON` double NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8


# --- !Downs

DROP TABLE IF EXISTS `MAP_POSITION`;
